
---
- name: Install default Apache WebServer
  hosts: all
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install Apache WebServer
    apt: name=apache2 state=latest

  - name: Start Apache and Enable it on every boot
    service: name=apache2 state=started enabled=yes
